# Title of the page
title: "Neil's Life"
# Your name
author: Neil Gupta
# Show a link to LinkedIn in the header intro. Comment out to disable.
linkedin: https://www.linkedin.com/in/guptaneil/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neil.gg
  title: neil.gg
# show today marker at end of timeline
show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - events:
    - October 1990: "ğŸ‘¶ Neil is born in Michigan."
    - December 1990: "âœˆï¸ Neil moves to California."
    - August 1994: "ğŸ‘¶ Neil's sister, Nandini, is born."
    - February 1995: "ğŸ’© Neil splatters poop on his walls while swinging a garbage bag with a dirty diaper. This is his first physics lesson."
    - December 1997: "ğŸ  Neil moves to his new home in south San Jose on Christmas. It's 100% less shitty than the last one."
    - July 1998: "ğŸ¬ Neil directs his first action movie using a VHS camcorder and PowerMac 8500."
    - March 1999: "ğŸ•¶ The Matrix is released. Neil has to clarify his name isn't Neo for the rest of the decade."
    - June 1999: "ğŸ”¥ Neil's parents upgrade their dial-up to 6mbps DSL. Neil starts playing with JavaScript. And Napster."
  - name: 2000's
    events:
    - October 2000: "ğŸ‚ Neil turns 10. It's a new millennium."
    - August 2002: "ğŸ“ Neil starts middle school."
    - August 2002: "ğŸ§® Neil gets a TI-83 Plus Silver Edition calculator that he uses to program games in BASIC during class."
    - July 2004: "ğŸ‘¨â€ğŸ’» Neil launches WebScope.tv, a video sharing platform for his friends because YouTube doesn't exist yet."
    - August 2004: "ğŸ“ Neil starts high school."
    - December 2005: "ğŸ‘¨â€ğŸ’» Neil cofounds Amalgam, an online literary magazine, and builds a NoSQL CMS to power it."
    - September 2006: "ğŸ‘¨â€ğŸ’» Neil cofounds Metamorphium Design, a profitable web design business."
    - May 2007: "ğŸ‘¨â€ğŸ’» Neil joins a sports social network as developer #1. He works out of a literal garage in Silicon Valley."
    - August 2007: "ğŸ“± Neil gets the first iPhone. People make fun of him for spending $600 on a phone."
    - August 2008: "âœˆï¸ Neil moves to Chicago."
    - November 2009: >-
        ğŸ“· Neil gets a DSLR camera and picks up <a href="https://photos.neil.gg" target="_blank" rel="noopener" 
        title="See some of my photos">photography as a hobby</a>.
  - name: 2010's
    events:
    - June 2010: "âœˆï¸ Neil spends a summer in Paris for study abroad."
    - October 2010: ğŸ‚ Neil turns 20.
    - October 2011: ğŸ† Neil becomes a ThinkChicago Fellow.
    - December 2011: >-
        ğŸ’» Neil works with <a href="https://vimeo.com/33098706" target="_blank" rel="noopener" title="Watch a slideshow of 
        my team's trip to Haiti">Haiti's Ministry of Education, OLPC, and IIT</a> to deploy solar panels, laptops, and servers pre-loaded with 
        Wikipedia in a Haitian school.
    - May 2012: >-
        ğŸ“ Neil graduates from Illinois Institute of Technology with degrees in Computer Science & Psychology, a minor in Entrepreneurship, 
        and a specialization in Artificial Intelligence.
    - June 2012: "ğŸ‘¨â€ğŸ’» Neil cofounds Tabule, a smart student planner powered by AI. It has over 4 stars in the App Store."
    - July 2012: >-
        ğŸ™ Neil does a <a href="https://vimeo.com/45029595" target="_blank" rel="noopener">press conference with Rahm Emanuel</a> about Tabule and 
        Chicago tech. Emanuel says "Chicago needs more Neils." Neil agrees for exactly 3 years.
    - June 2013: ğŸ’€ Tabule shuts down, the team is acqui-hired.
    - August 2014: >-
        ğŸ‘¨â€ğŸ’» Neil builds the <a href="https://vimeo.com/108903604" target="_blank" rel="noopener" title="Watch the 
        Flocks in action">Flocks</a>, an art installation that reacts to its environment. Cisco displays two at their Internet of Things 
        conference, 1871 displays four of them.
    - December 2014: >-
        ğŸ‘¨â€ğŸ’» Neil prototypes <a href="http://web.archive.org/web/20141219174007/http://www.getmaven.com/" target="_blank" 
        rel="noopener" title="Hurray for Wayback Machine!">Maven</a>, the operating system for your business, to automate mundane
        tasks with an email.
    - July 2015: ğŸ¤• Neil gets hit by a bicyclist named Neil G. He wakes up in the hospital with 14 stitches on his face but no new superpowers.
    - October 2015: ğŸ§§ Instructure IPO's.
    - November 2015: ğŸ  Neil buys his first home.
    - October 2016: "ğŸ’â€â™€ï¸ Neil meets Kat. His life is improved."
    - January 2018: ğŸ§  Neil builds an AI to manage his home for him.
    - September 2018: ğŸ›  Neil turns his second bedroom into a prototyping lab with four 3D printers and a soldering bench.
    - January 2019: ğŸ† Neil receives a grant from Y Combinator to keep building his smart home tech.
    - April 2019: >-
        ğŸ‘¨â€ğŸ’» Neil founds <a href="https://hiome.com" target="_blank" rel="noopener">Hiome</a> to change how we use our homes.
  - name: 2020's
    events:
    - January 2020: >-
        âœï¸ Neil <a href="https://github.com/neilgupta/timeliner" target="_blank" rel="noopener" title="Make your own!">writes this 
        timeline</a>. You're welcome.
    - May 2020: >-
        ğŸ¦  Neil launches <a href="https://researchexplained.org" target="_blank" rel="noopener">Research Explained</a> to make visual 
        summaries of COVID-19 research accessible to anyone.
    - July 2020: >-
        ğŸ’ Neil proposes to Kat!
